name: dbt CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  dbt:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dbt (duckdb adapter)
        run: |
          python -m pip install --upgrade pip
          pip install dbt-duckdb
      - name: Run dbt
        run: |
          dbt --version
          dbt deps || true
          # You'll need to supply a profiles.yml in CI or set up env secrets
          dbt seed --profiles-dir .github/profiles || true
          dbt run --profiles-dir .github/profiles
          dbt test --profiles-dir .github/profiles
